databases:
  - name: staffly-db
    databaseName: staffly
    user: staffly_user
    plan: free

services:
  - type: web
    name: staffly
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn staffly.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: staffly-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ENV
        value: production
      - key: ALLOWED_HOSTS
        sync: false
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: PYTHON_VERSION
        value: "3.11.0"
